import type { Question } from "../lib/types";
import bank from "./questions.json";

/**
 * Official ASP question bank (RU + RO), generated by
 * scripts/mreomd/fetch_autotest.py — edit the script, not questions.json.
 */
export const IS_DEMO_BANK = false;

export const QUESTIONS = bank as Question[];
