export type ColorSwatch = {
  name: string;
  hex: string;
};

export type ColorPalette = {
  label: string;
  swatches: ColorSwatch[];
};

export const NICHES: string[] = [
  "БРЕНД ПОСТЕЛЬНОГО БЕЛЬЯ",
  "БРЕНД ОДЕЖДЫ",
  "КОСМЕТИЧЕСКИЙ БРЕНД",
  "ЮВЕЛИРНЫЙ БРЕНД",
  "ЦВЕТОЧНАЯ МАСТЕРСКАЯ",
  "КОНДИТЕРСКАЯ",
  "КОФЕЙНЯ",
  "СТУДИЯ ДИЗАЙНА ИНТЕРЬЕРА",
  "ФИТНЕС-СТУДИЯ",
  "ЙОГА-СТУДИЯ",
  "БЬЮТИ-САЛОН",
  "БРЕНД СВЕЧЕЙ",
  "АРХИТЕКТУРНОЕ БЮРО",
  "АГЕНТСТВО НЕДВИЖИМОСТИ",
  "БРЕНД ОБУВИ",
  "БРЕНД АКСЕССУАРОВ",
  "ШКОЛА ТАНЦЕВ",
  "ФОТОСТУДИЯ",
  "БРЕНД ДЕТСКИХ ТОВАРОВ",
  "ВИННЫЙ БАР",
  "КНИЖНЫЙ МАГАЗИН",
  "ТАТУ-СТУДИЯ",
  "БРЕНД ПАРФЮМЕРИИ",
  "МАСТЕРСКАЯ КЕРАМИКИ",
  "БРЕНД СУМОК",
  "ШКОЛА СЁРФИНГА",
  "ПИТОМНИК РАСТЕНИЙ",
  "СТУДИЯ ПИЛАТЕСА",
  "БАР АВТОРСКИХ КОКТЕЙЛЕЙ",
  "МАРКЕТПЛЕЙС ХЕНДМЕЙДА",
  "АГЕНТСТВО СВАДЕБ",
  "СТУДИЯ ЗВУКОЗАПИСИ",
  "БРЕНД СПОРТИВНОЙ ОДЕЖДЫ",
  "ВЕТЕРИНАРНАЯ КЛИНИКА",
  "ПИТОМНИК СОБАК",
  "БРЕНД ТОВАРОВ ДЛЯ ЖИВОТНЫХ",
  "МАСТЕРСКАЯ МЕБЕЛИ",
  "СТУДИЯ ГОНЧАРНОГО ИСКУССТВА",
  "АГЕНТСТВО ПУТЕШЕСТВИЙ",
  "ГЛЭМПИНГ-ПАРК",
  "БРЕНД ЧАЯ",
  "РЕМЕСЛЕННАЯ ПИВОВАРНЯ",
  "СТУДИЯ ВОКАЛА",
  "ШКОЛА АРХИТЕКТУРЫ ДЛЯ ДЕТЕЙ",
  "БРЕНД ЭКО-КОСМЕТИКИ",
  "МАСТЕРСКАЯ ВИТРАЖЕЙ",
  "БРЕНД НАТУРАЛЬНОГО МЫЛА",
  "СТУДИЯ ПРОДЮСИРОВАНИЯ",
  "АГЕНТСТВО НЕЙМИНГА",
  "БРЕНД ОЧКОВ",
  "МАСТЕРСКАЯ КОЖАНЫХ ИЗДЕЛИЙ",
  "ШКОЛА КАЛЛИГРАФИИ",
  "СТУДИЯ ТАТУАЖА",
  "БРЕНД ДЕТСКОЙ ОДЕЖДЫ",
  "ПРОСТРАНСТВО ДЛЯ МЕДИТАЦИИ",
  "АГЕНТСТВО ИНТЕРЬЕРНОЙ ФОТОГРАФИИ",
  "БРЕНД АРОМАТОВ ДЛЯ ДОМА",
  "СТУДИЯ ФЛОРИСТИКИ",
  "МАРКЕТ ФЕРМЕРСКИХ ПРОДУКТОВ",
  "БРЕНД ВИНТАЖНОЙ МЕБЕЛИ",
  "ШКОЛА СЁРФ-ЙОГИ",
  "СТУДИЯ НЕЙЛ-АРТА",
  "БРЕНД ШОКОЛАДА",
  "АТЕЛЬЕ ПО ШИТЬЮ",
  "БРЕНД ДЛЯ БЕГА",
  "КУЛИНАРНАЯ СТУДИЯ",
  "БАР НАТУРАЛЬНЫХ ВИН",
  "СТУДИЯ АРОМАТЕРАПИИ",
];

export const MOODS: string[] = [
  "РОМАНТИКА",
  "МИНИМАЛИЗМ",
  "ДЕРЗОСТЬ",
  "НОСТАЛЬГИЯ",
  "РОСКОШЬ",
  "ИГРИВОСТЬ",
  "СПОКОЙСТВИЕ",
  "ЭНЕРГИЯ",
  "ЗАГАДОЧНОСТЬ",
  "ТЕПЛОТА",
  "СТРОГОСТЬ",
  "ЛЁГКОСТЬ",
  "ДРАМА",
  "НЕЖНОСТЬ",
  "СВОБОДА",
  "УВЕРЕННОСТЬ",
  "МЕЧТАТЕЛЬНОСТЬ",
  "ЭКСТРАВАГАНТНОСТЬ",
  "ЧИСТОТА",
  "СМЕЛОСТЬ",
  "ЭЛЕГАНТНОСТЬ",
  "ИСКРЕННОСТЬ",
  "ВДОХНОВЕНИЕ",
  "ГАРМОНИЯ",
  "ПРИТЯЖЕНИЕ",
  "ИНТРИГА",
  "УЮТ",
  "АЗАРТ",
  "ВЫЗОВ",
  "НЕВИННОСТЬ",
  "ЧУВСТВЕННОСТЬ",
  "ЯСНОСТЬ",
  "ВЕЛИЧИЕ",
  "ПРОСТОТА",
  "ДИНАМИКА",
  "СИЯНИЕ",
  "ТИШИНА",
  "БУНТАРСТВО",
  "ИЗЯЩЕСТВО",
  "ЖИВОСТЬ",
  "БЛАГОРОДСТВО",
  "АВАНТЮРИЗМ",
  "СОЛИДНОСТЬ",
  "ОТКРЫТОСТЬ",
  "ВЕСЕЛЬЕ",
  "ГЛУБИНА",
  "СВЕЖЕСТЬ",
  "ЯРКОСТЬ",
  "СДЕРЖАННОСТЬ",
  "ВООДУШЕВЛЕНИЕ",
  "ЧЕСТНОСТЬ",
  "УТОНЧЁННОСТЬ",
  "СИЛА",
  "СПОНТАННОСТЬ",
  "ГРАЦИЯ",
  "ТЁПЛАЯ НОСТАЛЬГИЯ",
  "ТИХАЯ УВЕРЕННОСТЬ",
];

export const NAMES: string[] = [
  "LINNET",
  "NOVARA",
  "SOLEIL",
  "VERUM",
  "AMBRE",
  "KAIRO",
  "LUMEN",
  "OPALINE",
  "SERENA",
  "VOLTA",
  "MERIDIAN",
  "ECHO",
  "ORLA",
  "ISSIMO",
  "VESTA",
  "NOMAD",
  "AURORA",
  "CASTLE",
  "FABULA",
  "PALOMA",
  "VANTA",
  "MIRAGE",
  "HALCYON",
  "QUILL",
  "SABLE",
  "ZEFIRO",
  "LUCERO",
  "NOVUS",
  "ORION",
  "TIDES",
  "EMBER",
  "ASTRA",
  "VELVET",
  "CORDA",
  "MAVEN",
  "NORDIC",
  "SOLSTICE",
  "PETRA",
  "IVORY",
  "RAVEL",
  "TUNDRA",
  "GLOW",
  "ARBOR",
  "CLARO",
  "FERN",
  "HAVEN",
  "LUNARA",
  "MOSSA",
  "PRISMA",
  "RIVIERA",
  "SAGE",
  "TERRA",
  "UMBRA",
  "VOYAGE",
  "WILLOW",
  "ZENITH",
  "BLOOM",
  "DUNE",
  "ECLAT",
  "FABLE",
  "MERIT",
  "OBLIQUE",
  "PALLOR",
  "QUIETA",
  "RUNWAY",
  "SILT",
];

export const PALETTES: ColorPalette[] = [
  {
    label: "NAVY INK + ROSE POWDER",
    swatches: [
      { name: "NAVY INK", hex: "#12183F" },
      { name: "ROSE POWDER", hex: "#F1B9CE" },
    ],
  },
  {
    label: "BONE + CASSIS",
    swatches: [
      { name: "BONE", hex: "#EDE6DA" },
      { name: "CASSIS", hex: "#4B1035" },
    ],
  },
  {
    label: "OLIVE + CREAM",
    swatches: [
      { name: "OLIVE", hex: "#6B6E3A" },
      { name: "CREAM", hex: "#F5F0E1" },
    ],
  },
  {
    label: "CHARCOAL + BLUSH",
    swatches: [
      { name: "CHARCOAL", hex: "#2B2B2B" },
      { name: "BLUSH", hex: "#F2C6C2" },
    ],
  },
  {
    label: "TERRACOTTA + SAND",
    swatches: [
      { name: "TERRACOTTA", hex: "#C0603A" },
      { name: "SAND", hex: "#E8D5B7" },
    ],
  },
  {
    label: "FOREST + IVORY",
    swatches: [
      { name: "FOREST", hex: "#1F3A2E" },
      { name: "IVORY", hex: "#F6F3EA" },
    ],
  },
  {
    label: "BURGUNDY + BEIGE",
    swatches: [
      { name: "BURGUNDY", hex: "#5A1F2A" },
      { name: "BEIGE", hex: "#E7DCC8" },
    ],
  },
  {
    label: "COBALT + PEACH",
    swatches: [
      { name: "COBALT", hex: "#1D3E9C" },
      { name: "PEACH", hex: "#F6C9A0" },
    ],
  },
  {
    label: "MUSTARD + GRAPHITE",
    swatches: [
      { name: "MUSTARD", hex: "#D9A83B" },
      { name: "GRAPHITE", hex: "#2E2E2E" },
    ],
  },
  {
    label: "LILAC + PLUM",
    swatches: [
      { name: "LILAC", hex: "#C9B6E4" },
      { name: "PLUM", hex: "#3E1F47" },
    ],
  },
  {
    label: "TEAL + CORAL",
    swatches: [
      { name: "TEAL", hex: "#1C5C55" },
      { name: "CORAL", hex: "#F08A6C" },
    ],
  },
  {
    label: "GOLD + ONYX",
    swatches: [
      { name: "GOLD", hex: "#C9A24B" },
      { name: "ONYX", hex: "#14141A" },
    ],
  },
  {
    label: "SAGE + CLAY",
    swatches: [
      { name: "SAGE", hex: "#9CAF88" },
      { name: "CLAY", hex: "#B5654A" },
    ],
  },
  {
    label: "INDIGO + BLUSH",
    swatches: [
      { name: "INDIGO", hex: "#2A2A72" },
      { name: "BLUSH", hex: "#F4C6D0" },
    ],
  },
  {
    label: "SLATE + AMBER",
    swatches: [
      { name: "SLATE", hex: "#45505A" },
      { name: "AMBER", hex: "#E1A94C" },
    ],
  },
  {
    label: "DUSTY ROSE + DEEP MOSS",
    swatches: [
      { name: "DUSTY ROSE", hex: "#C48B93" },
      { name: "DEEP MOSS", hex: "#3A4A34" },
    ],
  },
  {
    label: "BUTTER + ESPRESSO",
    swatches: [
      { name: "BUTTER", hex: "#F3D98B" },
      { name: "ESPRESSO", hex: "#3B2A20" },
    ],
  },
  {
    label: "POWDER BLUE + BRICK",
    swatches: [
      { name: "POWDER BLUE", hex: "#B9D3E0" },
      { name: "BRICK", hex: "#A6432F" },
    ],
  },
  {
    label: "ICE + MIDNIGHT",
    swatches: [
      { name: "ICE", hex: "#E7EEF2" },
      { name: "MIDNIGHT", hex: "#12131C" },
    ],
  },
  {
    label: "APRICOT + INK",
    swatches: [
      { name: "APRICOT", hex: "#F2A65A" },
      { name: "INK", hex: "#1B1B2B" },
    ],
  },
  {
    label: "SEAFOAM + WALNUT",
    swatches: [
      { name: "SEAFOAM", hex: "#A9D3C4" },
      { name: "WALNUT", hex: "#5A3E2B" },
    ],
  },
  {
    label: "BLUSH + BOTTLE GREEN",
    swatches: [
      { name: "BLUSH", hex: "#F1C7C2" },
      { name: "BOTTLE GREEN", hex: "#16352B" },
    ],
  },
  {
    label: "WHEAT + RUST",
    swatches: [
      { name: "WHEAT", hex: "#E8CE9B" },
      { name: "RUST", hex: "#A6421F" },
    ],
  },
  {
    label: "SMOKE + CORAL PINK",
    swatches: [
      { name: "SMOKE", hex: "#D8D3CC" },
      { name: "CORAL PINK", hex: "#F28B82" },
    ],
  },
  {
    label: "PERIWINKLE + CLAY RED",
    swatches: [
      { name: "PERIWINKLE", hex: "#A7B0E8" },
      { name: "CLAY RED", hex: "#B4502F" },
    ],
  },
  {
    label: "CREAM + AUBERGINE",
    swatches: [
      { name: "CREAM", hex: "#F5EFE3" },
      { name: "AUBERGINE", hex: "#3E1F33" },
    ],
  },
  {
    label: "STONE + COBALT BLUE",
    swatches: [
      { name: "STONE", hex: "#D6D0C4" },
      { name: "COBALT BLUE", hex: "#1F4FA6" },
    ],
  },
  {
    label: "HONEY + CHARCOAL",
    swatches: [
      { name: "HONEY", hex: "#E3A857" },
      { name: "CHARCOAL", hex: "#2A2A2A" },
    ],
  },
  {
    label: "LAVENDER + INK BLUE",
    swatches: [
      { name: "LAVENDER", hex: "#D8CCEC" },
      { name: "INK BLUE", hex: "#1A2340" },
    ],
  },
  {
    label: "SAND + FOREST GREEN",
    swatches: [
      { name: "SAND", hex: "#E4D3B0" },
      { name: "FOREST GREEN", hex: "#23422F" },
    ],
  },
];
